### ISSUE TITLE
Unable to create a cluster using empty without specifying storage

### ISSUE THREAD

**Issue by sebbonnet** [sky-uk/cassandra-operator#167]
Storage properties are not required when using emptyDir volumes and so it should be possible to create the following cluster definition:
```
apiVersion: core.sky.uk/v1alpha1
kind: Cassandra
metadata:
  name: mycluster
spec:
  useEmptyDir: true
  pod:
    image: "cassandra:3.11"
    cpu: "0"
    memory: 1Gi
    storageSize: "0"
  racks:
  - name: a
    replicas: 1
    storageClass: ""
    zone: ""
```

Yet when attempting to create the above cluster, the pods cannot be scheduled as the nodeAffinity rule is broken, with no value for the zone:
```
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: failure-domain.beta.kubernetes.io/zone
            operator: In
            values:
            - ""
``` 

Ideally we would want to remove the `useEmptyDir` properties and replace it by defining an emptyDir type of storage rather than a PV type. This idea was somewhat suggested here already: see https://github.com/sky-uk/cassandra-operator/issues/74
