### ISSUE TITLE
Unable to remove cpu request or limit using patch

### ISSUE THREAD

**Issue by sebbonnet** [sky-uk/cassandra-operator#181]
### Describe the bug
It isn't possible to remove cpu limit or request from an existing cluster.
This is because we are using a strategic merge patch strategy that doesn't allow to remove items.  

### Expected Behavior
Applying a Cassandra definition without `cpu` limit / request should remove the cpu limit / request from the StatefulSets

### Steps to Reproduce
Create a cluster with definition:
```
apiVersion: core.sky.uk/v1alpha1
kind: Cassandra
metadata:
  name: mycluster
spec:
  pod:
    resources:
      limits:
        cpu: "1"
        memory: 1.5Gi
      requests:
        cpu: 100m
        memory: 1Gi
    storageSize: "100Mi"
  racks:
  - name: a
    replicas: 1
    storageClass: "standard-zone-a"
    zone: "eu-west-1a"
```
Edit the cluster definition and remove cpu limit / request
The operator will create a patch which won't change the statefulset and will retry with the same outcome at the next reconciliation.
```
time="2019-09-04T16:36:07Z" level=info msg="Applying patch for rack a in cluster test-cassandra-operator.mycluster: {\n  \"spec\": {\n\t\"replicas\": 1,\n\t\"template\": {\n\t  \"spec\": {\n\t\t\"initContainers\": [{\n\t\t   \"name\": \"cassandra-bootstrapper\",\n\t\t   \"im
age\": \"skyuk/cassandra-bootstrapper:latest\"\n\t\t}],\n\t\t\"containers\": [{\n\t\t   \"name\": \"cassandra\",\n\t\t   \"livenessProbe\": {\n\t\t\t \"failureThreshold\": 3,\n\t\t\t \"initialDelaySeconds\": 30,\n\t\t\t \"periodSeconds\": 30,\n\t\t\t \"successThreshold\": 1,
\n\t\t\t \"timeoutSeconds\": 5\n\t\t   },\n\t\t   \"readinessProbe\": {\n\t\t\t \"failureThreshold\": 3,\n\t\t\t \"initialDelaySeconds\": 30,\n\t\t\t \"periodSeconds\": 15,\n\t\t\t \"successThreshold\": 1,\n\t\t\t \"timeoutSeconds\": 5\n\t\t   },\n\t\t   \"resources\": {\n\t
\t\t \"requests\": {\n               \t\n\t\t\t   \"memory\": \"1Gi\"\n\t\t\t },\n\t\t\t \"limits\": {\n               \n\t\t\t   \"memory\": \"1536Mi\"\n\t\t\t }\n\t\t   }\n\t\t},\n\t\t{\n\t\t   \"name\": \"cassandra-sidecar\",\n\t\t   \"image\": \"skyuk/cassandra-sidecar:l
atest\"\n\t\t}]\n\t  }\n\t}\n  }\n}"

```

We get the same results when trying to patch the statefulset manually using:
```
> kubectl --context kind -n test-cassandra-operator patch statefulset/mycluster-a -p "$(cat /tmp/thepatch.txt)" 
statefulset.apps/mycluster-a not patched
```

where `/tmp/thepatch.txt` is:
```
{
  "spec": {
        "template": {
          "spec": {
                "containers": [{
                   "name": "cassandra",
                   "resources": {
                         "requests": {
                           "memory": "1Gi"
                         },
                         "limits": {
                           "memory": "1.5Gi"
                         }
                   }
                }]
          }
        }
  }
}
```

### Your Environment
Include as many relevant details about the environment you experienced the bug in:
* Kubernetes version: 1.10
* Cassandra operator docker image: v0.72.0-alpha
