### ISSUE TITLE
Intermittent test failure due to unexpected pod restart

### ISSUE THREAD

**Issue by sebbonnet** [sky-uk/cassandra-operator#197]
### Describe the bug
The `creation_test.go` test suite sometimes fails as a pod in the 3-node cluster is unexpectedly restarted

```
[/home/travis/gopath/src/github.com/sky-uk/cassandra-operator/cassandra-operator/test/e2e/parallel/creation/creation_test.go:139

  Expected
      <int>: 1
  to equal
      <int>: 0
``` 

The build log shows there was a restart
```
==== Cluster mycluster-wz0l8 =====
NAME                  READY     STATUS    RESTARTS   AGE       IP           NODE
mycluster-wz0l8-a-0   2/2       Running   0          6m        10.244.4.4   kind-worker2
mycluster-wz0l8-a-1   2/2       Running   0          5m        10.244.3.4   kind-worker
mycluster-wz0l8-b-0   2/2       Running   1          3m        10.244.2.4   kind-worker4
```

Full build logs: [container-restarting-log-sidecar2.txt](https://github.com/sky-uk/cassandra-operator/files/3641441/container-restarting-log-sidecar2.txt)

### Your Environment
Include as many relevant details about the environment you experienced the bug in:
* Travis
* Kubernetes version: 1.11 (Kind)
* Cassandra operator docker image: cassandra:3.11
* Cassandra cluster definition - 
```
apiVersion: core.sky.uk/v1alpha1
kind: Cassandra
metadata:
  name: mycluster-wz0l8
  namespace: test-cassandra-operator
spec:
  datacenter: custom-dc
  pod:
    bootstrapperImage: localhost:5000/cassandra-bootstrapper:v20d3b51
    image: cassandra:3.11
    livenessProbe:
      failureThreshold: 4
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 7
    readinessProbe:
      failureThreshold: 8
      initialDelaySeconds: 30
      periodSeconds: 15
      timeoutSeconds: 6
    resources:
      limits:
        memory: 987Mi
      requests:
        cpu: 1m
        memory: 987Mi
    sidecarImage: localhost:5000/cassandra-sidecar:v20d3b51
  racks:
  - name: a
    replicas: 2
    storage:
    - path: /var/lib/pv-cassandra-home
      persistentVolumeClaim:
        resources:
          requests:
            storage: 100Mi
        storageClassName: standard-zone-a
    - emptyDir: {}
      path: /var/log/my-empty-dir
    zone: eu-west-1a
  - name: b
    replicas: 1
    storage:
    - path: /var/lib/pv-cassandra-home
      persistentVolumeClaim:
        resources:
          requests:
            storage: 100Mi
        storageClassName: standard-zone-b
    - emptyDir: {}
      path: /var/log/my-empty-dir
    zone: eu-west-1b
status: {}
```
