### ISSUE TITLE
Unable to create /var/lib/cassandra/data on EBS volumes

### ISSUE THREAD

**Issue by sebbonnet** [sky-uk/cassandra-operator#209]
### What is the bug being reported?
When provisioning a cluster with EBS as the backing storage, Cassandra pods are unable to start up due to wrong file permissions. Cassandra logs show:
```
WARN  [main] 2019-10-23 16:55:10,326 StartupChecks.java:332 - Directory /var/lib/cassandra/data doesn't exist                                                                                                                                                                                                                                                    
ERROR [main] 2019-10-23 16:55:10,327 CassandraDaemon.java:749 - Has no permission to create directory /var/lib/cassandra/data  
```

### If repeatable, how can we reproduce this issue?
This happens since `skyuk/cassandra-operator:v0.76.0-alpha`
I was able to create the same cluster with `skyuk/cassandra-operator:v0.75.0-alpha`.

### Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:
* Kubernetes version: 1.12
* Cassandra operator docker image: `skyuk/cassandra-operator:v0.76.0-alpha`
* Cassandra cluster definition - e.g. `kubectl get cassandra my_cluster -o yaml`: 
```
apiVersion: core.sky.uk/v1alpha1
kind: Cassandra
metadata:
  name: my-jaeger-cassandra
spec:
  datacenter: "jaegerspike"
  pod:
    image: "cassandra:3.11"
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 2Gi
  racks:
    - name: a
      replicas: 2
      storage:
        - persistentVolumeClaim:
            resources:
              requests:
                storage: 10Gi
            storageClassName: standard-zone-a
      zone: eu-west-1a
    - name: b
      replicas: 2
      storage:
        - persistentVolumeClaim:
            resources:
              requests:
                storage: 10Gi
            storageClassName: standard-zone-b
      zone: eu-west-1b
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard-zone-a
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: eu-west-1a
  fsType: xfs
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard-zone-b
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: eu-west-1b
  fsType: xfs
```
