### ISSUE TITLE
Node anti-affinity rules do not account for namespaces

### ISSUE THREAD

**Issue by alangibson01** [sky-uk/cassandra-operator#214]
### What is the bug being reported?
If there are two Cassandra definitions with the same name but in different namespaces, the node anti-affinity rules defined on the statefulsets created for those definitions will prevent Cassandra pods from the two clusters being scheduled to the same node. This is an unnecessary restriction.

### What would be the expected behavior?
Cassandra pods from two independent clusters should be schedulable on the same node, regardless of what their name is or what namespace they are defined in.

### If repeatable, how can we reproduce this issue?
Apply the following YAML:
```yaml
---
apiVersion: core.sky.uk/v1alpha1
kind: Cassandra
metadata:
  name: my-cassandra
  namespace: ns1
spec:
  datacenter: dc1
  pod:
    image: cassandra:3.11
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: "4"
        memory: 2Gi
  racks:
  - name: a
    replicas: 2
    storage:
    - persistentVolumeClaim:
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard-zone-a
    zone: eu-west-1a
  - name: b
    replicas: 2
    storage:
    - persistentVolumeClaim:
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard-zone-b
    zone: eu-west-1b
---
apiVersion: core.sky.uk/v1alpha1
kind: Cassandra
metadata:
  name: my-cassandra
  namespace: ns2
spec:
  datacenter: dc1
  pod:
    image: cassandra:3.11
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: "4"
        memory: 2Gi
  racks:
  - name: a
    replicas: 2
    storage:
    - persistentVolumeClaim:
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard-zone-a
    zone: eu-west-1a
  - name: b
    replicas: 2
    storage:
    - persistentVolumeClaim:
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard-zone-b
    zone: eu-west-1b
```

When these clusters are provisioned by the operator, Cassandra pods from `ns1/my-cassandra` and `ns2/my-cassandra` will never be scheduled to the same Kubernetes node.

### Workaround, if known
Ensure that Cassandra definitions in different namespaces have different names.
 
### Additional context
This problem would largely only affect Cassandra deployments where the number of pods per rack is close to the number of nodes in the Kubernetes cluster.

### Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:
* Kubernetes version: 1.12
* Cassandra operator docker image: v0.78.0-alpha

**Comment by alangibson01** [comment]
The labels we currently apply to pods in a Cassandra cluster are:

```yaml
app: my-jaeger-cassandra
rack: a
sky.uk/cassandra-operator: my-jaeger-cassandra
```

The pod anti-affinity rule we use is:

```yaml
requiredDuringSchedulingIgnoredDuringExecution:
- labelSelector:
    matchLabels:
      sky.uk/cassandra-operator: my-jaeger-cassandra
  topologyKey: kubernetes.io/hostname
```

The simple fix is to introduce the namespace into the value of the `sky.uk/cassandra-operator` label, but I'm wondering if we shouldn't also move to the [Common Labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) recommended in the Kubernetes docs.

In this approach, each cluster would have a unique value for `app.kubernetes.io/instance`. We'd probably do this just by adding the namespace as a prefix or suffix, but we'd be closer to the Kubernetes conventions than we are now.

@sebbonnet Thoughts ...?

**Comment by sebbonnet** [comment]
Using the common labels is a good idea.
I've seen other operators make use of them: for instance the jaeger operator adds these labels to jaeger-query pods:
```
 labels:                                                                                                                                                                                                                                                             
    app: jaeger                                                                                                                                                                                                                                                       
    app.kubernetes.io/component: query                                                                                                                                                                                                                                
    app.kubernetes.io/instance: my-jaeger                                                                                                                                                                                                                             
    app.kubernetes.io/managed-by: jaeger-operator                                                                                                                                                                                                                     
    app.kubernetes.io/name: my-jaeger-query                                                                                                                                                                                                                           
    app.kubernetes.io/part-of: jaeger           
```
