### ISSUE TITLE
In order to test the cassandra-snapshot module, do I need to deploy the operator ?

### ISSUE THREAD

**Issue by carlo4002** [sky-uk/cassandra-operator#226]
### The question
In order to test the cassandra-snapshot module, do I need to deploy the operator ?

**Comment by sebbonnet** [comment]
Thank you for your interest @carlo4002 

The `cassandra-snapshot` module is independent from the operator, so you do not need to deploy the operator to test it. However you will need to have a target Cassandra cluster running inside Kubernetes which is where you might find the cassandra-operator useful.

If you already have a Cassandra cluster running in Kubernetes, you can create a snapshot on demand by running a particular image of the `cassandra-snapshot` and specifying where to find the Cassandra pods using a label selector. This is explained here: https://github.com/sky-uk/cassandra-operator/wiki/Making-Snapshots#on-demand-snapshot-creation. 

You might also want to have a look at this end-to-end test where we create a set of Cassandra pods and then run the `cassandra-snapshot` as a pod to validate the snapshot creation works as expected:
https://github.com/sky-uk/cassandra-operator/blob/v0.81.0-alpha/cassandra-snapshot/test/e2e/create/create_test.go#L28
 
Let me know if you have a more specific use case, so I can try to help you further.

**Comment by carlo4002** [comment]
Hello @sebbonnet , thank you very much for your answer.

Yes I am testing it in my cluster k8s. I want to create a pod using this line

`create -n my_namespace -l sky.uk/cassandra-operator=my_cluster,app=my_cluster -k my_keyspace`

and I want to identify certains things I cannot understand.
-n is the namespace, I do not understand why it must be specify twice. 
-l is it the image to the operator ?

I guess app=my_cluster and sky.uk/cassandra-operator=my_cluster are the levels 

I appreciate your help

**Comment by carlo4002** [comment]
I have created a yaml to run the snapshot with this module 
`apiVersion: v1
kind: Pod
metadata:
  name: snapshot-pod
  labels:
    app: cassandracluster
spec:
  serviceAccountName: serviceaccount-jcarlo
  restartPolicy: Never
  containers:
    - command:
       - cassandra-snapshot
      name: snaposhot
      image: /k8s/cassandra-snapshot
      resources:
       limits:
         cpu: 50m
         memory: 8Gi
       requests:
         cpu: 50m
         memory: 8Gi
`
and when I apply the yaml, the container cannot find the commande create 
`OCI runtime create failed: container_linux.go:346: starting container process cau│
│sed "exec: \"cassandra-snapshot\": executable file not found in $PATH": unknown `

**Comment by sebbonnet** [comment]
> -n is the namespace, I do not understand why it must be specify twice.

You can run the snapshot job in a different namespace than your cassandra pod

>  -l is it the image to the operator

`-l` is the Kubernetes label assigned to the Cassandra pods - this is used by the `cassandra-snapshot` to identify which pods it should take a snapshot for.
If you run `docker run skyuk/cassandra-snapshot:v0.81.0-alpha --help` it will show you how you can use and configure the `cassandra-snapshot`. It will give you that:
```
Creates or cleans up snapshots of a cassandra cluster for one or more keyspaces

Usage:
  cassandra-snapshot [command]

Available Commands:
  cleanup     Removes snapshots of a cassandra cluster older than the retention period
  create      Creates snapshots of a cassandra cluster for one or more keyspaces
  help        Help about any command

Flags:
  -h, --help               help for cassandra-snapshot
  -k, --keyspace strings   Keyspace to snapshot. Repeat this flag to specify multiple values.
  -L, --log-level string   should be one of: debug, info, warn, error, fatal, panic (default "info")
  -n, --namespace string   Namespace where the cassandra pods are deployed
  -l, --pod-label string   Kubernetes labels attached to cassandra pods that are targeted. Comma-separated list

Use "cassandra-snapshot [command] --help" for more information about a command.
```

I don't fully understand your setup, so perhaps you can adapt the following examples to make it work for your use case (assuming that we operate in `test-cassandra-operator` namespace): 
- apply the `cassandra-pod.yml` to create a single Cassandra pod
- apply the `service.account.yml` to create a service account required by `cassandra-snapshot` to access Cassandra pod.
- run the below `kubectl` command to create a job which will take a snapshot

**cassandra-pod.yml**
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mycluster
  name: cassandra-pod
  namespace: test-cassandra-operator
spec:
  containers:
  - image: cassandra:3.11
    imagePullPolicy: IfNotPresent
    name: cassandra
    readinessProbe:
      exec:
        command:
        - cqlsh
        - -e
        - select * from system_auth.roles
```

**service.account.yml**
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cassandra-snapshot
  namespace: test-cassandra-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cassandra-snapshot
  namespace: test-cassandra-operator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cassandra-snapshot-binding
  namespace: test-cassandra-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cassandra-snapshot
subjects:
- kind: ServiceAccount
  name: cassandra-snapshot
  namespace: test-cassandra-operator
```

```
kubectl  run my-snapshot-taker -n test-cassandra-operator --serviceaccount=cassandra-snapshot --rm --attach --image=skyuk/cassandra-snapshot:v0.81.0-alpha -- create -n test-cassandra-operator -l app=mycluster -k system_auth                                                                                                                   
```
