### ISSUE TITLE
Sidecar Resource Table

### ISSUE THREAD

**Issue by chuckydev** [sky-uk/cassandra-operator#243]
## Motivation
The Cassandra Sidecar resources are currently hardcoded and assumed. It would be ideal that all resources are configurable in size based on all users needs. 

## Requirements

It would be ideal to seperate the sidercar configuration `sidecarImage` into a new subsection of pod called `sidecar`, this would be a breaking change but would save effort in the future by creating a clear seperation of configuration for each container. Below this we can state the resources required. .

**current configuration:**
```
  pod:
    bootstrapperImage: 
    sidecarImage: 
    image: 
    readinessProbe:
      timeoutSeconds: 
    resources:
      limits:
        memory: 
      requests:
        cpu: 
        memory: 
```
**potential configuration:**
```
  pod:
    bootstrapperImage: 
    image:
    readinessProbe:
      timeoutSeconds: 
    resources:
      limits:
        memory: 
      requests:
        cpu: 
        memory: 
    sidecar:
      image: 
      resources:
        requests:
          cpu: 
          memory: 
        limits:
          memory: 
```
## Alternatives
- Continue with fixed resources. 
- Not make a breaking change and have them grouped. Maybe no need to move sidecarImage yet but would be good to do as part of this feature

### Additional context
- We might want to do this for bootstrapper in the future.

## Tasks/Feature Set
- List tasks/features in order to meet the requirements listed above
- Refactor image to take from the sidercar block instead of the "pod" block
- Add Resources that follow the same validation as snapshot/pod validation rules
- Check Reconciler Tests to see whether individual fields of the main cassandra pod is tested.
