### ISSUE TITLE
Move Pod.StorageSize to Rack

### ISSUE THREAD

**Issue by kragniz** [sky-uk/cassandra-operator#78]
This should be located alongside `Rack.StorageClass`.

UDPDATE: @sebbonnet 
We're taking the opportunity the completely overhaul the way we define and handle rack storage as described here: https://github.com/sky-uk/cassandra-operator/issues/78#issuecomment-528850121
- [x] Allow multiple rack storage #184, #190 
- [x] Allow updates and removal of emptyDir storage #192  

Part of #33.

**Comment by alangibson01** [comment]
This would mean you could have different storage sizes on different racks, which I don't think you would want on a Cassandra cluster. The split of the token range across nodes would need to account for the different amounts of storage available on each node, which is not a scenario we see as being likely.

**Comment by wallrj** [comment]
@alangibson01 That makes sense. For comparison other C* operators :
 * Cluster level: https://github.com/Orange-OpenSource/cassandra-k8s-operator/blob/db2689105fa932a4ebc8a0cac49ddf438f4c00d7/pkg/apis/db/v1alpha1/cassandracluster_types.go#L620
 * Rack level: https://github.com/rook/rook/blob/release-1.0/Documentation/cassandra-cluster-crd.md#sample
 * Rack level: https://github.com/scylladb/scylla-operator/blob/master/docs/scylla_cluster_crd.md#sample
 * DC level: https://github.com/instaclustr/cassandra-operator/blob/master/examples/common/test.yaml#L26

**Comment by sebbonnet** [comment]
I can see the argument to move both storage class and size together.
As storage class cannot be moved to pod for the reason explained [here](https://github.com/sky-uk/cassandra-operator/pull/84#discussion_r283710410 ), the only option is to move both properties to Racks.

I get your point @alangibson01, but I think this decision would be up to the users.
Although we would recommend using the same disk type and size across all nodes, I don't think we want to prevent the users from doing it.

**Comment by sebbonnet** [comment]
Having all storage attributes together (zone, store class and size) makes sense and is arguably a better design. With our current structure the users could already have different underlying disk types for each rack, which is obviously a bad idea, but not something we should prevent.
Happy to reopen

**Comment by sebbonnet** [comment]
I think we should change our API to be closer to the Kubernetes API, so that users can be in full control of how they specify storage properties and so our API naturally evolves alongside Kubernetes. 

We support 2 types out of the numerous [volumes types](https://kubernetes.io/docs/concepts/storage/volumes/#types-of-volumes) Kubernetes supports: `persistentVolumeClaim` and `emptyDir`.

- For each volume we support, we should expose a property of the same name to make it both easier to add new volume types and relate to the Kubernetes volume types:
  - `persistentVolumeClaim` will be of type `v1.PersistentVolumeClaim`
  - `emptyDir` will be of type `v1.EmptyDirVolumeSource`
- In order to allow data and logs (and potentially more directories) to be stored on different volumes, we should have a storage block for each directory:
  - `default` for `/var/lib/cassandra`
  - in the future `log` for `/var/log/cassandra/` 
  - possibly more for nested mounts such as `data` for `/var/lib/cassandra/data` in which case each directory would need to be associated with a path 
- Directories would be located underneath a top level `storage` block
- Only one volume type would be accepted per directory.
- the zone property is not associated with the storage as it used to decide the node affinity, it should probably be part of another higher level entity, such as `affinity` or `placement` 

**Example of the current cluster definition using a PVC:**
```
apiVersion: core.sky.uk/v1alpha1
kind: Cassandra
metadata:
  name: mycluster-twomore
spec:
  pod:
    image: "cassandra:3.11"
    resources:
      requests:
        cpu: 1m
        memory: 1Gi
      limits:
        memory: 1Gi
    storageSize: 100Mi
  racks:
    - name: a
      replicas: 1
      storageClass: standard-zone-a
      zone: eu-west-1a
```

**Proposed cluster definition using a PVC:**
```
apiVersion: core.sky.uk/v1alpha1
kind: Cassandra
metadata:
  name: mycluster-twomore
spec:
  pod:
    image: "cassandra:3.11"
    resources:
      requests:
        cpu: 1m
        memory: 1Gi
      limits:
        memory: 1000Mi
  racks:
    - name: a
      replicas: 1
      storage:
        default:
          persistentVolumeClaim:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Mi
            storageClassName: standard-zone-a
      zone: eu-west-1a
```

**Proposed cluster definition using an emptyDir:**
```
apiVersion: core.sky.uk/v1alpha1
kind: Cassandra
metadata:
  name: mycluster-twomore
spec:
  pod:
    image: "cassandra:3.11"
    resources:
      requests:
        cpu: 1m
        memory: 1Gi
      limits:
        memory: 1000Mi
  racks:
    - name: a
      replicas: 1
      storage:
        lib:
          emptyDir: {}
      zone: eu-west-1a
```


**Proposed cluster definition with nested volumes:**
```
apiVersion: core.sky.uk/v1alpha1
kind: Cassandra
metadata:
  name: mycluster-twomore
spec:
  pod:
    image: "cassandra:3.11"
    resources:
      requests:
        cpu: 1m
        memory: 1Gi
      limits:
        memory: 1000Mi
  racks:
    - name: a
      replicas: 1
      storage:
        default:
          path: /var/lib/cassandra
          persistentVolumeClaim:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Mi
            storageClassName: standard-zone-a
        data:
          path: /var/lib/cassandra/data
            persistentVolumeClaim:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 100GI
              storageClassName: standard-zone-a
        logs:
          path: /var/logs/cassandra
          emptyDir: {}
      zone: eu-west-1a      
```

**Comment by alangibson01** [comment]
I appreciate the way this adds flexibility to the way that different kinds of storage can be used, especially because we can get rid of the clunkiness around the way we support `emptyDir` volumes. I can see how you might also want different volume types for your logs and your data, which would be handy.

I think we need to acknowledge, however, that this comes at the cost of making definition of a cluster more complicated. There's a certain amount of that we can cover off by making our examples straightforward, for example, using `emptyDir`.

The main thing, though, would be to make the API around storage as clear as we can, and for that reason I think that the entries in the `storage` list shouldn't have a `name` property - they should be identified solely by the path that they map to. I don't think having a storage entry with the name `default` gives a clear idea of its purpose - you could easily argue that `default` should correspond to the root volume.

**Comment by sebbonnet** [comment]
The `name` property under `storage` is not useful, I agree - I've now removed it.

I also think this setup would allow users to specify the file-system however they want with logs, config, and data in different volumes, even nested if they want. The operator would simply iterate over the list of volumes under the `storage` property with very little validation (e.g. unique path, path reserved).
I imagine most users would want to have at least `/var/logs/cassandra` and `/var/lib/cassandra` mounted in different volumes, with the first an `emptyDir` and the second a `PV`.

> One other thing has occurred to me - do we need to do any special handling of the case where we've got storage paths X and Y defined, where Y is a subpath of X? (e.g. /var/lib/cassandra and /var/lib/cassandra/data)

Nested volumes are supported, so this type of configuration is valid.
I've tested mounting a pod with several volume types with `/var/lib/cassandra/data` being a PV mounted as a nested volume of `/var/lib/cassandra`. This is probably not a configuration we would see many times, but is nonetheless possible.  Here is an extract of the pod spec, the full spec is available here: [cassandra-pod-mixed-volumes.yml](https://github.com/sky-uk/cassandra-operator/files/3590645/cassandra-pod-mixed-volumes.yml.txt): 
```
   volumeMounts:
    - mountPath: /etc/cassandra
      name: cassandra-storage-etc
    - mountPath: /var/logs/cassandra
      name: cassandra-storage-logs
    - mountPath: /var/lib/cassandra
      name: cassandra-storage-lib
    - mountPath: /var/lib/cassandra/data
      name: cassandra-storage-data
  volumes:
  - name: cassandra-storage-etc
    emptyDir: {}
  - name: cassandra-storage-logs
    emptyDir: {}
  - name: cassandra-storage-lib
    emptyDir: {}
  - name: cassandra-storage-data
    persistentVolumeClaim:
      claimName: mycluster-cassandra-data
  - name: mycluster-custom-config
    configMap:
      name: mycluster-custom-config
```

All 4 volumes were mounted on the pod:
```
root@mycluster-mixed-volumes:/# cat /proc/mounts | grep cassandra
/dev/nvme1n1p2 /etc/cassandra ext4 rw,relatime,errors=remount-ro 0 0
/dev/nvme1n1p2 /var/logs/cassandra ext4 rw,relatime,errors=remount-ro 0 0
/dev/nvme1n1p2 /var/lib/cassandra ext4 rw,relatime,errors=remount-ro 0 0
none /var/lib/cassandra/data aufs rw,relatime,si=e8d78e6e43241b86,dio,dirperm1 0 0
```
